### ISSUE TITLE
Angular 1.3 compatibility

### ISSUE THREAD

**Issue by mriccia** [Reactive-Extensions/rx.angular.js#75]
Are there any known issue of using this with Angular 1.3?

Looking at the source, I can see all of the examples and all of the tests are based on Angular 1.2.
I tried running tests against 1.3 and everything seems to pass but it would be good to have extra reassurance

**Comment by mattpodwysocki** [comment]
@mriccia there should be no breaking changes between 1.2 and 1.3.  We will update our test harness to ensure that it is using 1.3.

**Comment by mriccia** [comment]
Really glad to hear! If I find the time I'll create a pull request perhaps, I've never contributed to Open source software before but I'll give it a shot

**Comment by cognitronic** [comment]
I'm trying experimenting with angular-rx using Angular 1.3 with ControllerAs syntax and cant seem to get ahold of $createObservableFunction, just get an error saying undefined is not a function.  Do you have any examples using the ControllerAs syntax?

**Comment by HipsterZipster** [comment]
+1

**Comment by xgrommx** [comment]
Hi @cognitronic. I made some changes and rx-angular can working with angular 1.3 now. You can look on this https://github.com/Reactive-Extensions/rx.angular.js/blob/master/examples/%24createObservableFunctionAsController/app.js#L30
